AWSTemplateFormatVersion: 2010-09-09
Resources:
  GarageLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: garage-lambda
      Description: Test Lmabda
      Runtime: python3.8
      Code:
        ZipFile: |
          def handler(event, context):
              print "OK!!"
      Handler: app.handler
      Timeout: 120
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: garage-function-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: garage-function-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateExportTask
                  - s3:GetBucketAcl
                  - s3:PutObject

  GarageLambdaFunctionApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api
  GarageLambdaFunctionApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref GarageLambdaFunctionApi
      ParentId: !GetAtt GarageLambdaFunctionApi.RootResourceId
      PathPart: garage-lambda
    DependsOn:
      - GarageLambdaFunctionApi
      - GarageLambdaFunction
  GarageLambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: garage-lambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
    DependsOn:
      - GarageLambdaFunctionApiResource
  ResourceMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref GarageLambdaFunctionApi
      ResourceId: !Ref GarageLambdaFunctionApiResource
      AuthorizationType: None
      HttpMethod: POST
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:garage-lambda/invocations
    DependsOn: GarageLambdaFunctionPermission
