AWSTemplateFormatVersion: 2010-09-09
Resources:
  GarageLmabdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: garage-lambada
      Description: Test Lmabda
      Runtime: python3.8
      Code:
        ZipFile: |
          def handler(event, context):
              print "OK!!"
      Handler: app.handler
      Timeout: 120
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: garage-function-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: garage-function-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateExportTask
                  - s3:GetBucketAcl
                  - s3:PutObject